ktor:
    application:
        modules:
            - com.blackcube.ApplicationKt.module
    deployment:
        port: 8080

postgres:
    url: "jdbc:postgresql://localhost:5433/area"
    user: "postgres"
    password: "QHTKUTxr563"